<%@ Page Title="" Language="C#" MasterPageFile="~/View/Admin/AdminMaster.Master" AutoEventWireup="true" CodeBehind="Products.aspx.cs" Inherits="OnlineGrocery.View.Admin.Products" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="Mybody" runat="server">

    <div class="container-fluid">
        <div class="row">
            <div class="row">
                <div class="col-md-4"></div>
                <div class="col-md-8"><br /><img src="../../Asset/Images/vegetables.jpg" height="200px" width="200px"  /><h4 style="color: darkgreen">Manage Products</h4></div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <h2 class="text-success">Products Details</h2>

                <div class="mb-3">
                    <label>Product Name:</label>
                    <asp:TextBox ID="txtProdname" CssClass="form-control" runat="server"></asp:TextBox>
                </div>
                <div class="mb-3">
                    <label>Product Category:</label>
                    <asp:DropDownList ID="ddlprod" runat="server" CssClass="form-control"></asp:DropDownList>
                </div>
                <div class="mb-3">
                    <label>Product Price:</label>
                    <asp:TextBox ID="txtProdprice" CssClass="form-control" runat="server"></asp:TextBox>
                </div>
                <div class="mb-3">
                    <label>Product Quantity:</label>
                    <asp:TextBox ID="txtProdquan" CssClass="form-control" runat="server"></asp:TextBox>
                </div>
                <div class="mb-3">
                    <label>Expiry Date:</label>
                    <asp:TextBox ID="txtExpiry" runat="server" TextMode="Date"></asp:TextBox>
                </div>

                <label id="lblMsg" runat="server" class="text-success"></label><br />
                <asp:Button ID="btnEdit" runat="server" Text="   Edit   " class="btn btn-success" OnClick="btnEdit_Click" />
                <asp:Button ID="btnSave" runat="server" Text="   Save   " class="btn btn-success" OnClick="btnSave_Click"/>
            </div>
            <div class="col-md-8">
                <asp:GridView ID="dtgProduct" class="table table-hover" runat="server" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" OnSelectedIndexChanged="dtgProduct_SelectedIndexChanged" OnRowDeleting="dtgProduct_RowDeleting"></asp:GridView>
            </div>
        </div>
    </div>
</asp:Content>
